### ISSUE TITLE
Canonical org PRs counter is failing

### ISSUE THREAD

**Issue by goulinkh** [canonical/webteam-hubot#160]
`Here is the error in the logs:
``console
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'repositories' of null
  at requestPullRequests (/srv/scripts/github-pull-requests-reviews-notifications.js:67:37)
  at process._tickCallback (internal/process/next_tick.js:68:7)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 89)
```

**Comment by tbille** [comment]
I updated the secret used. I'll close this issue
thanks for reporting it  :smiley:
